<script setup lang="ts">
import {ref,onMounted} from "vue";import Button from "primevue/button";import Card from "primevue/card";import DataTable from "primevue/datatable";import Column from "primevue/column";import Select from "primevue/select";import InputNumber from "primevue/inputnumber";
const page=ref("Dashboard"),token=localStorage.getItem("passthrough-token")??"",health=ref<any>(),history=ref<any>({items:[]}),settings=ref<any>({defaultAction:"save",historyPageSize:20});const headers=()=>({Authorization:`Bearer ${token}`,"Content-Type":"application/json"});
async function load(){health.value=await fetch("/api/health").then(r=>r.json());if(token){history.value=await fetch("/api/history",{headers:headers()}).then(r=>r.json());settings.value=await fetch("/api/settings",{headers:headers()}).then(r=>r.json())}}
async function save(){await fetch("/api/settings",{method:"PUT",headers:headers(),body:JSON.stringify(settings.value)});await load()} onMounted(load);
</script>
<template><header><h1>Passthrough</h1><nav><Button v-for="p in ['Dashboard','History','Settings']" :key="p" :label="p" text @click="page=p"/></nav></header><main>
<template v-if="page==='Dashboard'"><div class="grid"><Card><template #title>API</template><template #content>{{health?.status??'Checking…'}}</template></Card><Card><template #title>Clipboard agent</template><template #content>{{health?.clipboardAgent?.status??'Unknown'}}</template></Card><Card><template #title>Upload directory</template><template #content>{{health?.uploadDirectory??'Unknown'}}</template></Card><Card><template #title>Recent transfers</template><template #content>{{history.total??0}}</template></Card></div></template>
<DataTable v-else-if="page==='History'" :value="history.items" paginator :rows="settings.historyPageSize"><Column field="timestamp" header="Timestamp"/><Column field="label" header="Item"/><Column field="mime_type" header="Type"/><Column field="byte_size" header="Size"/><Column field="action" header="Action"/><Column field="save_result" header="Save"/><Column field="clipboard_result" header="Clipboard"/></DataTable>
<Card v-else><template #title>Settings</template><template #content><form @submit.prevent="save"><label>Default action<Select v-model="settings.defaultAction" :options="['save','clipboard','both']"/></label><label>History page size<InputNumber v-model="settings.historyPageSize" :min="5" :max="100"/></label><Button type="submit" label="Save"/></form></template></Card>
</main></template>
