<script setup lang="ts">
import {ref,onMounted} from "vue";import Button from "primevue/button";import Card from "primevue/card";import DataTable from "primevue/datatable";import Column from "primevue/column";import Select from "primevue/select";import InputNumber from "primevue/inputnumber";
const page=ref("Dashboard"),token=ref(localStorage.getItem("passthrough-token")??""),enteredToken=ref(""),authError=ref(""),connecting=ref(false),health=ref<any>(),history=ref<any>({items:[]}),settings=ref<any>({defaultAction:"save",historyPageSize:20});const headers=(value=token.value)=>({Authorization:`Bearer ${value}`,"Content-Type":"application/json"});
async function load(value=token.value){health.value=await fetch("/api/health").then(r=>r.json());if(!value)return true;const [historyResponse,settingsResponse]=await Promise.all([fetch("/api/history",{headers:headers(value)}),fetch("/api/settings",{headers:headers(value)})]);if(historyResponse.status===401||settingsResponse.status===401)return false;if(!historyResponse.ok||!settingsResponse.ok)throw new Error("Unable to load Passthrough");history.value=await historyResponse.json();settings.value=await settingsResponse.json();return true}
function rejectToken(){localStorage.removeItem("passthrough-token");token.value="";authError.value="That token was rejected."}
async function connect(){connecting.value=true;authError.value="";try{if(!await load(enteredToken.value)){rejectToken();return}token.value=enteredToken.value;localStorage.setItem("passthrough-token",token.value);enteredToken.value=""}catch{authError.value="Unable to verify the token."}finally{connecting.value=false}}
async function save(){await fetch("/api/settings",{method:"PUT",headers:headers(),body:JSON.stringify(settings.value)});await load()}
onMounted(async()=>{if(token.value&&!await load())rejectToken()});
</script>
<template><header><h1>Passthrough</h1><nav v-if="token"><Button v-for="p in ['Dashboard','History','Settings']" :key="p" :label="p" text @click="page=p"/></nav></header><main>
<Card v-if="!token"><template #title>Connect to Passthrough</template><template #content><form @submit.prevent="connect"><label>Access token<input v-model="enteredToken" type="password" autocomplete="current-password" minlength="16" required autofocus></label><small v-if="authError" class="error" role="alert">{{authError}}</small><Button type="submit" label="Connect" :loading="connecting"/></form></template></Card>
<template v-else-if="page==='Dashboard'"><div class="grid"><Card><template #title>API</template><template #content>{{health?.status??'Checking…'}}</template></Card><Card><template #title>Clipboard agent</template><template #content>{{health?.clipboardAgent?.status??'Unknown'}}</template></Card><Card><template #title>Upload directory</template><template #content>{{health?.uploadDirectory??'Unknown'}}</template></Card><Card><template #title>Recent transfers</template><template #content>{{history.total??0}}</template></Card></div></template>
<DataTable v-else-if="page==='History'" :value="history.items" paginator :rows="settings.historyPageSize"><Column field="timestamp" header="Timestamp"/><Column field="label" header="Item"/><Column field="mime_type" header="Type"/><Column field="byte_size" header="Size"/><Column field="action" header="Action"/><Column field="save_result" header="Save"/><Column field="clipboard_result" header="Clipboard"/></DataTable>
<Card v-else><template #title>Settings</template><template #content><form @submit.prevent="save"><label>Default action<Select v-model="settings.defaultAction" :options="['save','clipboard','both']"/></label><label>History page size<InputNumber v-model="settings.historyPageSize" :min="5" :max="100"/></label><Button type="submit" label="Save"/></form></template></Card>
</main></template>
